apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microstore
  labels:
    app.kubernetes.io/part-of: microstore
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: "False"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: microstore
  POSTGRES_SSLMODE: disable
  REDIS_URL: redis://redis:6379/1
  AUTH_SERVICE_URL: http://auth-app:8010
  PRODUCTS_SERVICE_URL: http://products-app:8012
  CART_SERVICE_URL: http://cart-app:8013
  ORDERS_SERVICE_URL: http://orders-app:8014
  USER_SERVICE_URL: http://auth-app:8010/auth/user/
  PRODUCT_SERVICE_URL: http://products-app:8012/prd/
  CART_MIGRATION_URL: http://cart-app:8013/api/cart/migrate/
  AUTH_PUBLIC_URL: ""
