apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: microstore
  labels:
    app.kubernetes.io/part-of: microstore
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me-before-production
  POSTGRES_USER: microstore
  POSTGRES_PASSWORD: microstore-password
  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_EMAIL: admin@example.com
  DJANGO_SUPERUSER_PASSWORD: adminpass
