apiVersion: v1
kind: Service
metadata:
  name: cart-app
  namespace: microstore
  labels:
    app.kubernetes.io/name: cart-app
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: microstore
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cart-app
  ports:
    - name: http
      protocol: TCP
      port: 8013
      targetPort: http
