apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: microstore
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: microstore
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis
